django_3/accounts/urls.py
from django.urls import path
from .views import CreateUser, Login, LogOut

app_name = 'accounts'

urlpatterns = [
    path("signup/", CreateUser, name="CU"),
    path("login/", Login, name="LI"),
    path("logout/", LogOut, name="LO"),
]

django_3/blog/urls.py
from django.urls import path
from .views import (
    BlogView,
    DeleteBlogView,
    OneBlog,
    AddBlog,
    UpdateBlog,
) 

app_name = 'blog'

urlpatterns = [
    path("", BlogView.as_view(), name="BV"),
    path("add/", AddBlog.as_view(), name="AB"),
    path("one/<pk>/", OneBlog.as_view(), name="OB"),
    path("update/<pk>/", UpdateBlog.as_view(), name="UB"),
    path("delete/<pk>/", DeleteBlogView.as_view(), name="DB"),
]

django_3/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path("accounts/", include("accounts.urls"))
]

django_3/accounts/models.py
from django.db import models

# Create your models here.

django_3/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=300) # input
    blog = models.TextField() #textarea
    add_time = models.DateTimeField(auto_now_add=True)       
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:OB", kwargs={"pk": self.pk})
    

django_3/accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")

django_3/accounts/views.py
from .forms import NewUserForm
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
# Create your views here.

def CreateUser(request):
    form = NewUserForm
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Muaffaqiyatli bajarildi :) ")
            return redirect("accounts:LI")
    context = {
        "form":form,
    }
    return render(request, "register/signup.html", context)

def Login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"Xush kelibsiz {user.username}!")
                return redirect("blog:BV")
            messages.error(request, "Username yoki parol xato Afsus :( ")
        messages.error(request, "Username yoki parol xato Afsus :( ")
        
    form = AuthenticationForm
    return render(request, "register/login.html", {"form": form})
        
def LogOut(request):
    logout(request)
    messages.info(request, "Ko'rishguncha")
    return redirect("blog:BV")

django_3/blog/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic import DetailView
from django.views.generic.edit import (
    CreateView, 
    UpdateView, 
    DeleteView
)
from .models import Blog    

# Create your views here.

class BlogView(ListView):
    model = Blog
    ordering = '-add_time'
    template_name = "blogs.html"

class OneBlog(DetailView):
    model = Blog
    template_name = "one.html"

class AddBlog(CreateView):
    model = Blog
    template_name = "add.html"
    fields = ["title", "blog"]
    

class UpdateBlog(UpdateView):
    model = Blog
    template_name = "update.html"
    fields = ["title", "blog"]
    
class DeleteBlogView(DeleteView):
    model = Blog
    template_name = 'delete.html'
    success_url = '/'
    
    

django_3/templates/add.html
{% extends "base.html" %}

{% block title %}
    Add
{% endblock title %}

{% block content %}
    <div class="my-5">
        <a href="{% url 'blog:BV' %}">Back To Home</a>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Blog" name="bnt">
    </form>
{% endblock content %}

django_3/templates/alerts.html
{% if messages %}
    {% for ms in messages %}  
        <div class="alert {{ ms.tags }} alert-dismissible fade show" role="alert">
            {{ ms }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

django_3/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
          
        {% endblock title %} |
        MY BLOG
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    {% include "alerts.html" %}
    <div class="container">
        {% block content %}
          
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

django_3/templates/blogs.html
{% extends "base.html" %}
{% block title %}
    Home
{% endblock title %}

{% block content %}
    <div class="my-5">
        {% if user.is_authenticated %}
            <h1 class="user">{{ user.username }}</h1>
            <a href="{% url 'blog:AB' %}">Add Blog</a> |
            <a href="{% url 'accounts:LO' %}">LogOut</a>
        {% else %}
            <a href="{% url 'accounts:CU' %}">Register User</a> | 
            <a href="{% url 'accounts:LI' %}">Login</a>
        {% endif %}
    </div>
    <div class="row mt-5">
        {% for i in object_list %}
            <div class="col-xxl-8 m-auto">
                <div class="card mb-3">
                    <h5 class="card-header">{{ i.author.username }}</h5>
                    <div class="card-body">
                        <h5 class="card-title">{{ i.title }}</h5>
                        <p class="card-text">{{ i.blog | slice:250 }}</p>
                        <a href="{% url 'blog:OB' pk=i.pk %}" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>  
            </div>
        {% endfor %}
    </div>
{% endblock content %}

django_3/templates/delete.html
<form action="" method="post">
    {% csrf_token %}
    <h1>Sen haqiqatdan ham bu {{ object.title | slice:25 }}..... objectni o'chirishni xoxlaysanmi?</h1>
    <p> <mark>Warning</mark> qayta tiklash imkonsiz! </p>
    <input type="submit" class="btn btn-danger" value="Yes I am Sure">
    <a href="{% url 'blog:BV' %}" class="text-info">Cancel</a>
</form>

django_3/templates/one.html
{% extends "base.html" %}
{% block title %}
    Blog
{% endblock title %}
{% block content %}
    <a href="{% url 'blog:BV' %}" class="mt-5 btn btn-outline-dark">Back To Home</a>
    <div class="row mt-5">
        <div class="col-xxl-8 m-auto">
            <div class="card mb-3">
                <h5 class="card-header">{{ object.author.username }}</h5>
                <div class="card-body">
                    <h5 class="card-title">{{ object.title }}</h5>
                    <p class="card-text">{{ object.blog }}</p>
                    <a href="{% url 'blog:UB' pk=object.pk %}">Update</a> |
                    <a href="{% url 'blog:DB' pk=object.pk %}">Delete</a>
                </div>
            </div>  
        </div>
    </div>
{% endblock content %}

django_3/templates/register/login.html
{% extends "base.html" %}

{% block title %}
    LogIn
{% endblock title %}

{% block content %}
    <div class="my-5">
        <a href="{% url 'blog:BV' %}">Back To Home</a>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
{% endblock content %}

django_3/templates/register/signup.html
{% extends "base.html" %}

{% block title %}
    SignUp
{% endblock title %}

{% block content %}
    <div class="my-5">
        <a href="{% url 'blog:BV' %}">Back To Home</a>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock content %}

django_3/templates/update.html
{% extends "base.html" %}

{% block title %}
    Update
{% endblock title %}

{% block content %}
    <div class="my-5">
        <a href="{% url 'blog:BV' %}">Back To Home</a>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update Blog">
    </form>
{% endblock content %}